# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

production:
  nyt_api_key: 174a1ee32de36322b246700bfa57630c:0:74036157
  sunlight_api_key: 9f19d387e7904184af2eb15c6c1d7bc5
  consumer_key:	SdkfdG62LzGPiyxEqcLZ61uY6
  consumer_secret: cchuyEImEKQtopPxjiJKdiOAG8dBromi1w152GVtKatfxJbB63
  secret_key_base: c21a4ac4171bc1e890ca072f723809fc6a99eca076d0f7eb4ea1b4d597f0244b0f3354f98704f42910618ceebeae1d8acebc179e36d9ca98291d4234c27fd4c2
  access_token: 250190173-ldL1USW7XETgWP58wcqqtQJPjXy2sbSOPpow9aAF
  access_token_secret: mEPfDqtOSbRUoejXdDCWEvF3hrzQ8gyf44xSxLf42u4mf



development:
  nyt_api_key: 174a1ee32de36322b246700bfa57630c:0:74036157
  sunlight_api_key: 9f19d387e7904184af2eb15c6c1d7bc5
  consumer_key: ojhC635qkbrtyOBeHR8EwpYae
  consumer_secret: l9j0w1B5DKcaP72mKbIlkEyzHXLsN8LPRwEJEFu43AL19LsSRg
  access_token: 250190173-MN8iVf1K9beGsMiPUxnUfUIP35S2Y4BiksA5Xg9A
  access_token_secret: eeVUy71bObUkbqJUuepZEuTFHfXAPTjMpPfg1IPXj7IIo


test:
  nyt_api_key: 174a1ee32de36322b246700bfa57630c:0:74036157
  sunlight_api_key: 9f19d387e7904184af2eb15c6c1d7bc5
  uid: 250190173
  consumer_key: ojhC635qkbrtyOBeHR8EwpYae
  consumer_secret: l9j0w1B5DKcaP72mKbIlkEyzHXLsN8LPRwEJEFu43AL19LsSRg
  oauth_token: 250190173-MN8iVf1K9beGsMiPUxnUfUIP35S2Y4BiksA5Xg9A
  oauth_token_secret: eeVUy71bObUkbqJUuepZEuTFHfXAPTjMpPfg1IPXj7IIo
